name: Python CI and CD

on:
  push:
    branches: [ main, master ]

jobs:
   run-tests: #This is the Job ID.
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4 #actions/checkout 这个动作，就相当于在这台空白电脑上自动执行了 git clone 命令，把你的仓库代码下载下来，放到一个指定的工作目录里
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Run Python script
      run: python a.py  # 改成你的文件名
  # ========== CD: 上传文件到 Release ==========
   upload-release:
    needs: run-tests #必须run-test执行成功
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        # 不指定 files，只上传 GitHub 自动生成的源码包
        generate_release_notes: true
  
